### ISSUE TITLE
Bugs in buffaloZiGate.ts ?

### ISSUE THREAD

**Issue by peterbb** [Koenkk/zigbee-herdsman#313]
In `src/adapter/zigate/driver/buffaloZiGate.ts` there is the following code:
```javascript
const mac = this.readUInt8();
result.alternatePanCoordinator = !!(mac.mac & 0b00000001);
```

That doesn't seem to make any sense: readUInt8 returns a number, which doesn't have any property `mac`. Am I missing something? I don't have hardware to test it.

There is another similar thing happening in the `write` method in the same file. 
```javascript
        } else if (type === 'IEEADDR') {
            return this.readIeeeAddr();
```
Is it right that the `write`-method calls `read`? And the method has return type `void`, so why return a string?
Similar just below:
```javascript
        } else if (type === 'ADDRESS_WITH_TYPE_DEPENDENCY') {
            const addressMode = this.buffer.readUInt8(this.position - 1);
            return addressMode == 3 ? this.writeIeeeAddr(value) : this.writeUInt16BE(value);
```
Does it make sense to have a return here?

**Comment by Koenkk** [comment]
@G1K can you check this?

**Comment by G1K** [comment]
@peterbb Yes, you are right, these are flaws in the code.
1) MACCAPABILITY is not used anywhere in the application, parsing has been inherited.
2) In `write`, you can remove it, it was added due to the difference in the IEEADDR byte order that was transmitted by zigate and the one that comes from the zigbee network, but gradually I had to get away from zigate messages and use RAW mode, so this is also an unused piece of code.
3) In the third case, return is unnecessary, but does not break the application.
Yes, I know the code is far from ideal, and it is even used (ts-ignore, istanbul ignore) by analogy with neighboring adapters for example deconz, but it works)

All pull requests that improves the adapter code are welcome.
